use crate::diagnostics::AntiLlmDiagnostic;
use crate::observations::Observation;

pub fn evaluate(obs: &[Observation]) -> Vec<AntiLlmDiagnostic> {
    let mut diags = Vec::new();

    for o in obs {
        // Check for test result treated as receipt
        if o.construct == "test result: ok" {
            diags.push(AntiLlmDiagnostic {
                code: "ANTI-LLM-RECEIPT-001".to_string(),
                category: "receipt".to_string(),
                file_path: o.file_path.clone(),
                line: o.line,
                column: o.column,
                message: "Test stdout treated as receipt. Test output is not a cryptographically signed receipt.".to_string(),
                forbidden_implication: "TestStdout => Receipt".to_string(),
                blocking: true,
                required_correction: "Write process evidence into a BLAKE3/SHA-256 JSON receipt file instead of asserting on stdout.".to_string(),
                required_next_proof: "Verify receipt exists on disk with a valid BLAKE3 hash.".to_string(),
            });
        }

        // Check for log message treated as receipt
        if o.construct == "LogMessage => Receipt" || o.message.contains("LogMessage => Receipt") {
            diags.push(AntiLlmDiagnostic {
                code: "ANTI-LLM-RECEIPT-002".to_string(),
                category: "receipt".to_string(),
                file_path: o.file_path.clone(),
                line: o.line,
                column: o.column,
                message: "Log message treated as receipt. Logging is not admission/process evidence.".to_string(),
                forbidden_implication: "LogMessage => Receipt".to_string(),
                blocking: true,
                required_correction: "Produce a proper json receipt for actions instead of logging them.".to_string(),
                required_next_proof: "Verify receipt is generated by the MutationGate.".to_string(),
            });
        }

        // Check for missing receipt path
        if o.message.contains("Receipt file lacks required field")
            || o.construct == "missing digest"
        {
            diags.push(AntiLlmDiagnostic {
                code: "ANTI-LLM-RECEIPT-003".to_string(),
                category: "receipt".to_string(),
                file_path: o.file_path.clone(),
                line: o.line,
                column: o.column,
                message: "Receipt path or required field is missing.".to_string(),
                forbidden_implication: "Claimed proof => receipt exists".to_string(),
                blocking: true,
                required_correction:
                    "Make sure receipt file exists and conforms to receipt schema.".to_string(),
                required_next_proof:
                    "Verify receipt fields (digest, raw_command, boundary) are complete."
                        .to_string(),
            });
        }
    }

    diags
}
