&[
    MethodEntry {
        fn_name: "completion",
        lsp_method: "textDocument/completion",
        params_type: "CompletionParams",
        return_type: "Result<Option<CompletionResponse>>",
        capability_field: Some("completion_provider"),
        domain: Domain::Editing,
    },
    MethodEntry {
        fn_name: "completion_resolve",
        lsp_method: "completionItem/resolve",
        params_type: "CompletionItem",
        return_type: "Result<CompletionItem>",
        capability_field: Some("completion_provider"),
        domain: Domain::Editing,
    },
    MethodEntry {
        fn_name: "hover",
        lsp_method: "textDocument/hover",
        params_type: "HoverParams",
        return_type: "Result<Option<Hover>>",
        capability_field: Some("hover_provider"),
        domain: Domain::Editing,
    },
    MethodEntry {
        fn_name: "signature_help",
        lsp_method: "textDocument/signatureHelp",
        params_type: "SignatureHelpParams",
        return_type: "Result<Option<SignatureHelp>>",
        capability_field: Some("signature_help_provider"),
        domain: Domain::Editing,
    },
    MethodEntry {
        fn_name: "code_action",
        lsp_method: "textDocument/codeAction",
        params_type: "CodeActionParams",
        return_type: "Result<Option<CodeActionResponse>>",
        capability_field: Some("code_action_provider"),
        domain: Domain::Editing,
    },
    MethodEntry {
        fn_name: "code_action_resolve",
        lsp_method: "codeAction/resolve",
        params_type: "CodeAction",
        return_type: "Result<CodeAction>",
        capability_field: Some("code_action_provider"),
        domain: Domain::Editing,
    },
    MethodEntry {
        fn_name: "rename",
        lsp_method: "textDocument/rename",
        params_type: "RenameParams",
        return_type: "Result<Option<WorkspaceEdit>>",
        capability_field: Some("rename_provider"),
        domain: Domain::Editing,
    },
    MethodEntry {
        fn_name: "prepare_rename",
        lsp_method: "textDocument/prepareRename",
        params_type: "TextDocumentPositionParams",
        return_type: "Result<Option<PrepareRenameResponse>>",
        capability_field: Some("rename_provider"),
        domain: Domain::Editing,
    },
    MethodEntry {
        fn_name: "formatting",
        lsp_method: "textDocument/formatting",
        params_type: "DocumentFormattingParams",
        return_type: "Result<Option<Vec<TextEdit>>>",
        capability_field: Some("document_formatting_provider"),
        domain: Domain::Editing,
    },
    MethodEntry {
        fn_name: "range_formatting",
        lsp_method: "textDocument/rangeFormatting",
        params_type: "DocumentRangeFormattingParams",
        return_type: "Result<Option<Vec<TextEdit>>>",
        capability_field: Some("document_range_formatting_provider"),
        domain: Domain::Editing,
    },
    MethodEntry {
        fn_name: "on_type_formatting",
        lsp_method: "textDocument/onTypeFormatting",
        params_type: "DocumentOnTypeFormattingParams",
        return_type: "Result<Option<Vec<TextEdit>>>",
        capability_field: Some("document_on_type_formatting_provider"),
        domain: Domain::Editing,
    },
    MethodEntry {
        fn_name: "inline_completion",
        lsp_method: "textDocument/inlineCompletion",
        params_type: "InlineCompletionParams",
        return_type: "Result<Option<InlineCompletionResponse>>",
        capability_field: Some("inline_completion_provider"),
        domain: Domain::Editing,
    },
    MethodEntry {
        fn_name: "linked_editing_range",
        lsp_method: "textDocument/linkedEditingRange",
        params_type: "LinkedEditingRangeParams",
        return_type: "Result<Option<LinkedEditingRanges>>",
        capability_field: Some("linked_editing_range_provider"),
        domain: Domain::Editing,
    },
    MethodEntry {
        fn_name: "document_color",
        lsp_method: "textDocument/documentColor",
        params_type: "DocumentColorParams",
        return_type: "Result<Vec<ColorInformation>>",
        capability_field: Some("color_provider"),
        domain: Domain::Editing,
    },
    MethodEntry {
        fn_name: "color_presentation",
        lsp_method: "textDocument/colorPresentation",
        params_type: "ColorPresentationParams",
        return_type: "Result<Vec<ColorPresentation>>",
        capability_field: Some("color_provider"),
        domain: Domain::Editing,
    },
    MethodEntry {
        fn_name: "ranges_formatting",
        lsp_method: "textDocument/rangesFormatting",
        params_type: "max_protocol::lsp_3_18::DocumentRangesFormattingParams",
        return_type: "Result<Option<Vec<max_protocol::lsp_3_18::TextEdit>>>",
        capability_field: Some("document_formatting_provider"),
        domain: Domain::Editing,
    },
    MethodEntry {
        fn_name: "diagnostic",
        lsp_method: "textDocument/diagnostic",
        params_type: "DocumentDiagnosticParams",
        return_type: "Result<DocumentDiagnosticReportResult>",
        capability_field: Some("diagnostic_provider"),
        domain: Domain::Diagnostics,
    },
    MethodEntry {
        fn_name: "workspace_diagnostic",
        lsp_method: "workspace/diagnostic",
        params_type: "WorkspaceDiagnosticParams",
        return_type: "Result<WorkspaceDiagnosticReport>",
        capability_field: Some("diagnostic_provider"),
        domain: Domain::Diagnostics,
    },
]
