&[
    MethodEntry {
        fn_name: "initialize",
        lsp_method: "initialize",
        params_type: "InitializeParams",
        return_type: "Result<InitializeResult>",
        capability_field: None,
        domain: Domain::Lifecycle,
    },
    MethodEntry {
        fn_name: "initialized",
        lsp_method: "initialized",
        params_type: "InitializedParams",
        return_type: "()",
        capability_field: None,
        domain: Domain::Lifecycle,
    },
    MethodEntry {
        fn_name: "shutdown",
        lsp_method: "shutdown",
        params_type: "()",
        return_type: "Result<()>",
        capability_field: None,
        domain: Domain::Lifecycle,
    },
    MethodEntry {
        fn_name: "did_open",
        lsp_method: "textDocument/didOpen",
        params_type: "DidOpenTextDocumentParams",
        return_type: "()",
        capability_field: Some("text_document_sync"),
        domain: Domain::TextSync,
    },
    MethodEntry {
        fn_name: "did_change",
        lsp_method: "textDocument/didChange",
        params_type: "DidChangeTextDocumentParams",
        return_type: "()",
        capability_field: Some("text_document_sync"),
        domain: Domain::TextSync,
    },
    MethodEntry {
        fn_name: "did_save",
        lsp_method: "textDocument/didSave",
        params_type: "DidSaveTextDocumentParams",
        return_type: "()",
        capability_field: Some("text_document_sync"),
        domain: Domain::TextSync,
    },
    MethodEntry {
        fn_name: "did_close",
        lsp_method: "textDocument/didClose",
        params_type: "DidCloseTextDocumentParams",
        return_type: "()",
        capability_field: Some("text_document_sync"),
        domain: Domain::TextSync,
    },
    MethodEntry {
        fn_name: "will_save",
        lsp_method: "textDocument/willSave",
        params_type: "WillSaveTextDocumentParams",
        return_type: "()",
        capability_field: Some("text_document_sync"),
        domain: Domain::TextSync,
    },
    MethodEntry {
        fn_name: "will_save_wait_until",
        lsp_method: "textDocument/willSaveWaitUntil",
        params_type: "WillSaveTextDocumentParams",
        return_type: "Result<Option<Vec<TextEdit>>>",
        capability_field: Some("text_document_sync"),
        domain: Domain::TextSync,
    },
    MethodEntry {
        fn_name: "did_open_notebook_document",
        lsp_method: "notebookDocument/didOpen",
        params_type: "max_protocol::lsp_3_18::DidOpenNotebookDocumentParams",
        return_type: "()",
        capability_field: Some("notebook_document_sync"),
        domain: Domain::TextSync,
    },
    MethodEntry {
        fn_name: "did_change_notebook_document",
        lsp_method: "notebookDocument/didChange",
        params_type: "max_protocol::lsp_3_18::DidChangeNotebookDocumentParams",
        return_type: "()",
        capability_field: Some("notebook_document_sync"),
        domain: Domain::TextSync,
    },
    MethodEntry {
        fn_name: "did_save_notebook_document",
        lsp_method: "notebookDocument/didSave",
        params_type: "max_protocol::lsp_3_18::DidSaveNotebookDocumentParams",
        return_type: "()",
        capability_field: Some("notebook_document_sync"),
        domain: Domain::TextSync,
    },
    MethodEntry {
        fn_name: "did_close_notebook_document",
        lsp_method: "notebookDocument/didClose",
        params_type: "max_protocol::lsp_3_18::DidCloseNotebookDocumentParams",
        return_type: "()",
        capability_field: Some("notebook_document_sync"),
        domain: Domain::TextSync,
    },
]
