&[
    MethodEntry {
        fn_name: "goto_definition",
        lsp_method: "textDocument/definition",
        params_type: "GotoDefinitionParams",
        return_type: "Result<Option<GotoDefinitionResponse>>",
        capability_field: Some("definition_provider"),
        domain: Domain::Navigation,
    },
    MethodEntry {
        fn_name: "goto_declaration",
        lsp_method: "textDocument/declaration",
        params_type: "GotoDeclarationParams",
        return_type: "Result<Option<GotoDeclarationResponse>>",
        capability_field: Some("declaration_provider"),
        domain: Domain::Navigation,
    },
    MethodEntry {
        fn_name: "goto_type_definition",
        lsp_method: "textDocument/typeDefinition",
        params_type: "GotoTypeDefinitionParams",
        return_type: "Result<Option<GotoTypeDefinitionResponse>>",
        capability_field: Some("type_definition_provider"),
        domain: Domain::Navigation,
    },
    MethodEntry {
        fn_name: "goto_implementation",
        lsp_method: "textDocument/implementation",
        params_type: "GotoImplementationParams",
        return_type: "Result<Option<GotoImplementationResponse>>",
        capability_field: Some("implementation_provider"),
        domain: Domain::Navigation,
    },
    MethodEntry {
        fn_name: "references",
        lsp_method: "textDocument/references",
        params_type: "ReferenceParams",
        return_type: "Result<Option<Vec<Location>>>",
        capability_field: Some("references_provider"),
        domain: Domain::Navigation,
    },
    MethodEntry {
        fn_name: "document_highlight",
        lsp_method: "textDocument/documentHighlight",
        params_type: "DocumentHighlightParams",
        return_type: "Result<Option<Vec<DocumentHighlight>>>",
        capability_field: Some("document_highlight_provider"),
        domain: Domain::Navigation,
    },
    MethodEntry {
        fn_name: "prepare_call_hierarchy",
        lsp_method: "textDocument/prepareCallHierarchy",
        params_type: "CallHierarchyPrepareParams",
        return_type: "Result<Option<Vec<CallHierarchyItem>>>",
        capability_field: Some("call_hierarchy_provider"),
        domain: Domain::Navigation,
    },
    MethodEntry {
        fn_name: "incoming_calls",
        lsp_method: "callHierarchy/incomingCalls",
        params_type: "CallHierarchyIncomingCallsParams",
        return_type: "Result<Option<Vec<CallHierarchyIncomingCall>>>",
        capability_field: Some("call_hierarchy_provider"),
        domain: Domain::Navigation,
    },
    MethodEntry {
        fn_name: "outgoing_calls",
        lsp_method: "callHierarchy/outgoingCalls",
        params_type: "CallHierarchyOutgoingCallsParams",
        return_type: "Result<Option<Vec<CallHierarchyOutgoingCall>>>",
        capability_field: Some("call_hierarchy_provider"),
        domain: Domain::Navigation,
    },
    MethodEntry {
        fn_name: "moniker",
        lsp_method: "textDocument/moniker",
        params_type: "MonikerParams",
        return_type: "Result<Option<Vec<Moniker>>>",
        capability_field: Some("moniker_provider"),
        domain: Domain::Navigation,
    },
]
