&[
    MethodEntry {
        fn_name: "document_symbol",
        lsp_method: "textDocument/documentSymbol",
        params_type: "DocumentSymbolParams",
        return_type: "Result<Option<DocumentSymbolResponse>>",
        capability_field: Some("document_symbol_provider"),
        domain: Domain::Symbols,
    },
    MethodEntry {
        fn_name: "symbol",
        lsp_method: "workspace/symbol",
        params_type: "WorkspaceSymbolParams",
        return_type: "Result<Option<Vec<SymbolInformation>>>",
        capability_field: Some("workspace_symbol_provider"),
        domain: Domain::Symbols,
    },
    MethodEntry {
        fn_name: "prepare_type_hierarchy",
        lsp_method: "textDocument/prepareTypeHierarchy",
        params_type: "TypeHierarchyPrepareParams",
        return_type: "Result<Option<Vec<TypeHierarchyItem>>>",
        capability_field: Some("type_hierarchy_provider"),
        domain: Domain::Symbols,
    },
    MethodEntry {
        fn_name: "supertypes",
        lsp_method: "typeHierarchy/supertypes",
        params_type: "TypeHierarchySupertypesParams",
        return_type: "Result<Option<Vec<TypeHierarchyItem>>>",
        capability_field: Some("type_hierarchy_provider"),
        domain: Domain::Symbols,
    },
    MethodEntry {
        fn_name: "subtypes",
        lsp_method: "typeHierarchy/subtypes",
        params_type: "TypeHierarchySubtypesParams",
        return_type: "Result<Option<Vec<TypeHierarchyItem>>>",
        capability_field: Some("type_hierarchy_provider"),
        domain: Domain::Symbols,
    },
    MethodEntry {
        fn_name: "code_lens",
        lsp_method: "textDocument/codeLens",
        params_type: "CodeLensParams",
        return_type: "Result<Option<Vec<CodeLens>>>",
        capability_field: Some("code_lens_provider"),
        domain: Domain::CodeLens,
    },
    MethodEntry {
        fn_name: "code_lens_resolve",
        lsp_method: "codeLens/resolve",
        params_type: "CodeLens",
        return_type: "Result<CodeLens>",
        capability_field: Some("code_lens_provider"),
        domain: Domain::CodeLens,
    },
    MethodEntry {
        fn_name: "document_link",
        lsp_method: "textDocument/documentLink",
        params_type: "DocumentLinkParams",
        return_type: "Result<Option<Vec<DocumentLink>>>",
        capability_field: Some("document_link_provider"),
        domain: Domain::CodeLens,
    },
    MethodEntry {
        fn_name: "document_link_resolve",
        lsp_method: "documentLink/resolve",
        params_type: "DocumentLink",
        return_type: "Result<DocumentLink>",
        capability_field: Some("document_link_provider"),
        domain: Domain::CodeLens,
    },
    MethodEntry {
        fn_name: "inlay_hint",
        lsp_method: "textDocument/inlayHint",
        params_type: "InlayHintParams",
        return_type: "Result<Option<Vec<InlayHint>>>",
        capability_field: Some("inlay_hint_provider"),
        domain: Domain::CodeLens,
    },
    MethodEntry {
        fn_name: "inlay_hint_resolve",
        lsp_method: "inlayHint/resolve",
        params_type: "InlayHint",
        return_type: "Result<InlayHint>",
        capability_field: Some("inlay_hint_provider"),
        domain: Domain::CodeLens,
    },
    MethodEntry {
        fn_name: "folding_range",
        lsp_method: "textDocument/foldingRange",
        params_type: "FoldingRangeParams",
        return_type: "Result<Option<Vec<FoldingRange>>>",
        capability_field: Some("folding_range_provider"),
        domain: Domain::CodeLens,
    },
    MethodEntry {
        fn_name: "selection_range",
        lsp_method: "textDocument/selectionRange",
        params_type: "SelectionRangeParams",
        return_type: "Result<Option<Vec<SelectionRange>>>",
        capability_field: Some("selection_range_provider"),
        domain: Domain::CodeLens,
    },
    MethodEntry {
        fn_name: "inline_value",
        lsp_method: "textDocument/inlineValue",
        params_type: "InlineValueParams",
        return_type: "Result<Option<Vec<InlineValue>>>",
        capability_field: Some("inline_value_provider"),
        domain: Domain::CodeLens,
    },
    MethodEntry {
        fn_name: "semantic_tokens_full",
        lsp_method: "textDocument/semanticTokens/full",
        params_type: "SemanticTokensParams",
        return_type: "Result<Option<SemanticTokensResult>>",
        capability_field: Some("semantic_tokens_provider"),
        domain: Domain::SemanticTokens,
    },
    MethodEntry {
        fn_name: "semantic_tokens_full_delta",
        lsp_method: "textDocument/semanticTokens/full/delta",
        params_type: "SemanticTokensDeltaParams",
        return_type: "Result<Option<SemanticTokensFullDeltaResult>>",
        capability_field: Some("semantic_tokens_provider"),
        domain: Domain::SemanticTokens,
    },
    MethodEntry {
        fn_name: "semantic_tokens_range",
        lsp_method: "textDocument/semanticTokens/range",
        params_type: "SemanticTokensRangeParams",
        return_type: "Result<Option<SemanticTokensRangeResult>>",
        capability_field: Some("semantic_tokens_provider"),
        domain: Domain::SemanticTokens,
    },
]
