&[
    MethodEntry {
        fn_name: "execute_command",
        lsp_method: "workspace/executeCommand",
        params_type: "ExecuteCommandParams",
        return_type: "Result<Option<Value>>",
        capability_field: Some("execute_command_provider"),
        domain: Domain::Workspace,
    },
    MethodEntry {
        fn_name: "symbol_resolve",
        lsp_method: "workspaceSymbol/resolve",
        params_type: "WorkspaceSymbol",
        return_type: "Result<WorkspaceSymbol>",
        capability_field: Some("workspace_symbol_provider"),
        domain: Domain::Workspace,
    },
    MethodEntry {
        fn_name: "did_change_configuration",
        lsp_method: "workspace/didChangeConfiguration",
        params_type: "DidChangeConfigurationParams",
        return_type: "()",
        capability_field: None,
        domain: Domain::Workspace,
    },
    MethodEntry {
        fn_name: "did_change_workspace_folders",
        lsp_method: "workspace/didChangeWorkspaceFolders",
        params_type: "DidChangeWorkspaceFoldersParams",
        return_type: "()",
        capability_field: Some("workspace.workspaceFolders"),
        domain: Domain::Workspace,
    },
    MethodEntry {
        fn_name: "did_change_watched_files",
        lsp_method: "workspace/didChangeWatchedFiles",
        params_type: "DidChangeWatchedFilesParams",
        return_type: "()",
        capability_field: None,
        domain: Domain::Workspace,
    },
    MethodEntry {
        fn_name: "will_create_files",
        lsp_method: "workspace/willCreateFiles",
        params_type: "CreateFilesParams",
        return_type: "Result<Option<WorkspaceEdit>>",
        capability_field: Some("workspace.fileOperations"),
        domain: Domain::Workspace,
    },
    MethodEntry {
        fn_name: "did_create_files",
        lsp_method: "workspace/didCreateFiles",
        params_type: "CreateFilesParams",
        return_type: "()",
        capability_field: Some("workspace.fileOperations"),
        domain: Domain::Workspace,
    },
    MethodEntry {
        fn_name: "will_rename_files",
        lsp_method: "workspace/willRenameFiles",
        params_type: "RenameFilesParams",
        return_type: "Result<Option<WorkspaceEdit>>",
        capability_field: Some("workspace.fileOperations"),
        domain: Domain::Workspace,
    },
    MethodEntry {
        fn_name: "did_rename_files",
        lsp_method: "workspace/didRenameFiles",
        params_type: "RenameFilesParams",
        return_type: "()",
        capability_field: Some("workspace.fileOperations"),
        domain: Domain::Workspace,
    },
    MethodEntry {
        fn_name: "will_delete_files",
        lsp_method: "workspace/willDeleteFiles",
        params_type: "DeleteFilesParams",
        return_type: "Result<Option<WorkspaceEdit>>",
        capability_field: Some("workspace.fileOperations"),
        domain: Domain::Workspace,
    },
    MethodEntry {
        fn_name: "did_delete_files",
        lsp_method: "workspace/didDeleteFiles",
        params_type: "DeleteFilesParams",
        return_type: "()",
        capability_field: Some("workspace.fileOperations"),
        domain: Domain::Workspace,
    },
    MethodEntry {
        fn_name: "text_document_content",
        lsp_method: "workspace/textDocumentContent",
        params_type: "TextDocumentContentParams",
        return_type: "Result<TextDocumentContentResult>",
        capability_field: Some("text_document_content_provider"),
        domain: Domain::Workspace,
    },
    MethodEntry {
        fn_name: "text_document_content_refresh",
        lsp_method: "workspace/textDocumentContent/refresh",
        params_type: "max_protocol::lsp_3_18::TextDocumentContentRefreshParams",
        return_type: "Result<()>",
        capability_field: Some("text_document_content_provider"),
        domain: Domain::Workspace,
    },
    MethodEntry {
        fn_name: "work_done_progress_cancel",
        lsp_method: "window/workDoneProgress/cancel",
        params_type: "max_protocol::lsp_3_18::WorkDoneProgressCancelParams",
        return_type: "()",
        capability_field: None,
        domain: Domain::Window,
    },
    MethodEntry {
        fn_name: "progress",
        lsp_method: "$/progress",
        params_type: "max_protocol::lsp_3_18::ProgressParams",
        return_type: "()",
        capability_field: None,
        domain: Domain::Window,
    },
    MethodEntry {
        fn_name: "set_trace",
        lsp_method: "$/setTrace",
        params_type: "max_protocol::lsp_3_18::SetTraceParams",
        return_type: "()",
        capability_field: None,
        domain: Domain::Window,
    },
    MethodEntry {
        fn_name: "max_snapshot",
        lsp_method: "max/snapshot",
        params_type: "()",
        return_type: "Result<SnapshotId>",
        capability_field: None,
        domain: Domain::Max,
    },
    MethodEntry {
        fn_name: "max_conformance_vector",
        lsp_method: "max/conformanceVector",
        params_type: "MaxConformanceVectorParams",
        return_type: "Result<MaxConformanceVector>",
        capability_field: None,
        domain: Domain::Max,
    },
    MethodEntry {
        fn_name: "max_explain_diagnostic",
        lsp_method: "max/explainDiagnostic",
        params_type: "String",
        return_type: "Result<MaxDiagnostic>",
        capability_field: None,
        domain: Domain::Max,
    },
    MethodEntry {
        fn_name: "max_repair_plan",
        lsp_method: "max/repairPlan",
        params_type: "String",
        return_type: "Result<Vec<MaxCodeAction>>",
        capability_field: None,
        domain: Domain::Max,
    },
    MethodEntry {
        fn_name: "max_run_gate",
        lsp_method: "max/runGate",
        params_type: "GateId",
        return_type: "Result<bool>",
        capability_field: None,
        domain: Domain::Max,
    },
    MethodEntry {
        fn_name: "max_receipt",
        lsp_method: "max/receipt",
        params_type: "String",
        return_type: "Result<Receipt>",
        capability_field: None,
        domain: Domain::Max,
    },
    MethodEntry {
        fn_name: "max_clear_diagnostic",
        lsp_method: "max/clearDiagnostic",
        params_type: "String",
        return_type: "Result<()>",
        capability_field: None,
        domain: Domain::Max,
    },
    MethodEntry {
        fn_name: "max_apply_repair_transaction",
        lsp_method: "max/applyRepairTransaction",
        params_type: "MaxRepairTransaction",
        return_type: "Result<MaxRepairResult>",
        capability_field: None,
        domain: Domain::Max,
    },
    MethodEntry {
        fn_name: "max_export_analysis_bundle",
        lsp_method: "max/exportAnalysisBundle",
        params_type: "MaxExportBundleParams",
        return_type: "Result<MaxAnalysisBundle>",
        capability_field: None,
        domain: Domain::Max,
    },
    MethodEntry {
        fn_name: "max_dump_state",
        lsp_method: "max/dumpState",
        params_type: "()",
        return_type: "Result<serde_json::Value>",
        capability_field: None,
        domain: Domain::Max,
    },
    MethodEntry {
        fn_name: "max_restore_state",
        lsp_method: "max/restoreState",
        params_type: "serde_json::Value",
        return_type: "Result<()>",
        capability_field: None,
        domain: Domain::Max,
    },
]
